sonar.projectKey=lab3-devops
sonar.projectName=Lab3 DevSecOps
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.git/**,**/vendor/**,**/tests/**,**/*.test.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality Gate
sonar.qualitygate.wait=true

# Encoding
sonar.sourceEncoding=UTF-8
